name: Filter community resources

on:
  workflow_dispatch:
  # the workflow it also triggered when the community definitions are changed
  push:
    paths:
    - 'data/communities/*/metadata/*'
    branches: ["main"]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "filter"
  cancel-in-progress: false

jobs:
  filter-resources:
    name: Filter resources for communities
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Install requirement
      run: python -m pip install -r requirements.txt
    - name: Filter tutorials for communities
      run: | 
        bash bin/get_community_tutorials.sh
    - name: Update tool to keep and exclude for communities
      run: | 
        bash bin/update_tools_to_keep_exclude.sh
    - name: Filter tools for communities
      run: | 
        bash bin/get_community_tools.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update resources
        title: Resource filtering
        body: Resource filering done via GitHub Action when the community definitions are changed 
        base: main
        branch: resource-filtering
        delete-branch: true
