name: Filter community tools

on:
  workflow_dispatch:

  # the workflow it triggered when all tools are fetched
  workflow_run:
      workflows: ["Fetch all tools"]
      types:
        - completed

  # the workflow it also triggered when the community definitions are changed
  push:
    paths:
    - 'data/communities**'
    branches: ["main"]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "filter"
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  filter-all-tools:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8' 
    - name: Install requirement
      run: python -m pip install -r requirements.txt
    - name: Run script
      run: | 
        bash ./bin/get_community_tools.sh
    - name: Commit results
      # commit the new filtered data, only if stuff was changed
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull --no-rebase -s recursive -X ours
        git add results
        git status
        git diff --quiet && git diff --staged --quiet || (git commit -m "fetch all tools bot  - step filter") 
        git push
  
  filter-all-tutorials:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8' 
    - name: Install requirement
      run: python -m pip install -r requirements.txt
    - name: Run script
      run: | 
        bash ./bin/get_community_tutorials.sh
    - name: Commit results
      # commit the new filtered data, only if stuff was changed
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull --no-rebase -s recursive -X ours
        git add results
        git status
        git diff --quiet && git diff --staged --quiet || (git commit -m "fetch all tutorials bot  - step filter") 
        git push
